Mobile-menu Peer Review
udberg/mobile-menu pull request #1
Opened 2021-09-03 22:41 UTC by udberg

The learning objectives of this project include 
- `The use of basic Javascript syntax.`
- `The use of Javascript to manipulate DOM elements.`
- `The use of Javascript events.`

I implemented the following features for the mobile version of this project

- `When the user clicks (or taps) the hamburger button, the mobile menu appears.`
- `When the user clicks (or taps) the close (X) button, the mobile menu disappears.`
- `When the user clicks (or taps) any of the mobile menu options, the mobile menu disappears.`
- `When the user clicks (or taps) any of the mobile menu options, a correct part of the page is displayed.`

The project design can be found [Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).

2021-09-05 00:39 UTC, DanSam5K requested changes
## Hi @udberg, 🤝 

### Good job so far! 👏  🌱 
You have really put in a great amount of time and effort to make this project.

** Highlights ** 💪 
- You really 🔨 nailed your pull request message and seems to have correctly made all linters check pass 👍 . Also, your commit history and project setup are great as well.
- But there are some issues that you still need to work on to go to the next project but you are almost there! ☺️ 

## Required Changes ♻️
_Check the comments under the review._
- [ ] Noticed when the user clicks (or taps) the close (X) button, the mobile menu seems not to disappears. kindly fix that 👍 
- [ ] When the user clicks (or taps) any of the mobile menu options, a correct part of the page is displayed. You can do this: kindly check that also 🤗 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ] [Optional] how about you adding more links menu to the project as implemented by the actual [Figma design](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/images/m7_mobile_menu/menu-mobile.png) for this project, what do you think? 🤔 

I would really ❤️  to see your next version of this project it would be amazing! 🤗 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-05 00:39 UTC, DanSam5K commented on README.md
> +
- [ ] kindly fix the screenshot image it seems to be broken.

2021-09-05 00:39 UTC, DanSam5K commented on css/header.css
> +/* Start query */
- [ ] Would be nice you take out all commented code, as is often considered a good practice. 👍

2021-09-06 18:02 UTC, BrianSammit requested changes
# CHANGES REQUIRED :red_circle: 🛑 

Hi @udberg, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
Check the comments under the review. 👇 

## Optional suggestions 👌 

- [ ] [OPTIONAL] wouldn't be better if the mobile menu disappears when the user clicks (or taps) any option. Because when you click one of the options it will seem that the page does not make any change. 👌 🛠️ 

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.


----------
Please fix these minor errors and sen it again for another review :+1: :100: 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
# HAPPY CODING!!! 😄 

![200 (1)](https://user-images.githubusercontent.com/64173189/128109485-382fcc99-cf3c-4534-a70a-51351dfd9b39.gif)

**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-09-13 17:59 UTC, uwadonat requested changes
Hi **@Udberg**, 

Great work on making the changes requested by a previous reviewer 👏  now mobile menu disappear when the user clicks (or taps) the close (X) button :mechanical_arm: :beer: 

You've done well implementing some of the requested changes, It shows that you are able. but there are still some which aren't addressed yet.

 ## Required Changes ♻️
- Kindly check the remaining changes requested by the previous reviewer and work on them. 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- Since the previous reviewer didn't notice, this requirement is optional but recommended to be done: 

- [ ] Please make sure that when the user clicks (or taps) any of the mobile menu options, the mobile menu disappears.

   _Hope to see you celebrating soon_ :dancing_men: 
   Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-09-18 08:56 UTC, merged